// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calc/calc.proto

/*
Package calc is a generated protocol buffer package.

It is generated from these files:
	calc/calc.proto

It has these top-level messages:
	Number
	Numbers
*/
package calc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Number struct {
	Num string `protobuf:"bytes,1,opt,name=num" json:"num,omitempty"`
}

func (m *Number) Reset()                    { *m = Number{} }
func (m *Number) String() string            { return proto.CompactTextString(m) }
func (*Number) ProtoMessage()               {}
func (*Number) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Number) GetNum() string {
	if m != nil {
		return m.Num
	}
	return ""
}

type Numbers struct {
	Num1 string `protobuf:"bytes,1,opt,name=num1" json:"num1,omitempty"`
	Num2 string `protobuf:"bytes,2,opt,name=num2" json:"num2,omitempty"`
}

func (m *Numbers) Reset()                    { *m = Numbers{} }
func (m *Numbers) String() string            { return proto.CompactTextString(m) }
func (*Numbers) ProtoMessage()               {}
func (*Numbers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Numbers) GetNum1() string {
	if m != nil {
		return m.Num1
	}
	return ""
}

func (m *Numbers) GetNum2() string {
	if m != nil {
		return m.Num2
	}
	return ""
}

func init() {
	proto.RegisterType((*Number)(nil), "calc.Number")
	proto.RegisterType((*Numbers)(nil), "calc.Numbers")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Calculator service

type CalculatorClient interface {
	Add(ctx context.Context, in *Numbers, opts ...grpc.CallOption) (*Number, error)
}

type calculatorClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorClient(cc *grpc.ClientConn) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Add(ctx context.Context, in *Numbers, opts ...grpc.CallOption) (*Number, error) {
	out := new(Number)
	err := grpc.Invoke(ctx, "/calc.Calculator/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Calculator service

type CalculatorServer interface {
	Add(context.Context, *Numbers) (*Number, error)
}

func RegisterCalculatorServer(s *grpc.Server, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Numbers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calc.Calculator/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Add(ctx, req.(*Numbers))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calc.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Calculator_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calc/calc.proto",
}

func init() { proto.RegisterFile("calc/calc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4e, 0xcc, 0x49,
	0xd6, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x92, 0x14, 0x17,
	0x9b, 0x5f, 0x69, 0x6e, 0x52, 0x6a, 0x91, 0x90, 0x00, 0x17, 0x73, 0x5e, 0x69, 0xae, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0xa9, 0x64, 0xc8, 0xc5, 0x0e, 0x91, 0x2b, 0x16, 0x12, 0xe2,
	0x62, 0xc9, 0x2b, 0xcd, 0x35, 0x84, 0xca, 0x82, 0xd9, 0x50, 0x31, 0x23, 0x09, 0x26, 0xb8, 0x98,
	0x91, 0x91, 0x11, 0x17, 0x97, 0x73, 0x62, 0x4e, 0x72, 0x69, 0x4e, 0x62, 0x49, 0x7e, 0x91, 0x90,
	0x0a, 0x17, 0xb3, 0x63, 0x4a, 0x8a, 0x10, 0xaf, 0x1e, 0xd8, 0x5a, 0xa8, 0x59, 0x52, 0x3c, 0xc8,
	0x5c, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x7b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x41, 0xba,
	0x7c, 0x88, 0xa2, 0x00, 0x00, 0x00,
}
